### ISSUE TITLE
Add correct type instantiation parsing

### ISSUE THREAD

**Issue by CohenArthur** [CohenArthur/jinko#158]
Once #149 is merged, we'll have working custom types (❤️ @Skallwar) that aren't getting initialized completely properly.

```rust
> type Custom(a: int, b: float, s: string);
> c = Custom{1, 2.0, "custom"};
```

However, what we need to achieve is more strictness regarding initialization

```rust
> type Custom(a: int, b: float, s: string);
> c = Custom{1, 2.0, "custom"}; // Error
> c = Custom{ a =1, b = 2.0, s = "custom" }; // OK
> c = Custom { b = 2.0, a = 1, s = "custom" }; // OK? Error?
```

I'd like to discuss the behavior of custom instantiation here. This work will also pave the way for named arguments, that we might
want to add to function declarations and function calls later!

**Comment by Skallwar** [comment]
I think option number 3 
``` rust
 c = Custom { b = 2.0, a = 1, s = "custom" };
```
is the best solution. It's easy, and if the fields in the type move around and change position this will still work and no (user) code need to be changed
